user_pref('extensions.blocklist.pingCountVersion', 0);
user_pref('extensions.lastAppVersion', "0.10.3");
user_pref('extensions.lastPlatformVersion', "52.5.3");
user_pref('general.appname.override', "Netscape");
user_pref('general.appversion.override', "5.0 (Windows)");
user_pref('general.buildID.override', "20100101");
user_pref('general.oscpu.override', "Windows NT 6.1");
user_pref('general.platform.override', "Win32");
user_pref('general.productSub.override', "20100101");
user_pref('general.useragent.override', "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0");
user_pref('intl.accept_languages', "en-US, en");
user_pref('media.gmp.storage.version.observed', 1);
user_pref('media.peerconnection.enabled', false);
user_pref('network.cookie.cookieBehavior', 1);
user_pref('network.dns.disablePrefetch', true);
user_pref('network.proxy.type', 1);
user_pref('network.proxy.socks', "127.0.0.1");
user_pref('network.proxy.socks_remote_dns', true);
user_pref('network.proxy.proxy_over_tls', true);
user_pref('network.proxy.socks_port', 9040);
user_pref('marionette.port', 2828);